language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mueller@me.com
  api_key:
    secure: V+1Pw18vaiYkFP9zD5Nm+FpwYS9bS6LVVWfy9unl58vL6pFcHibNZlS0fUbvNx3YVGaWBFHoEwR+yga3iIUDfSndDn8gCJ8b0WBUIpKCMaa/XgVf2usJV5fa/rDRFdqVGb3qJhcS8ig2g1NMTMBLAmJrWbsiFK6cE4PF7FrSO03MZGSkRBwfnUxhs8YufNIoQkGjk0fDUQWU7/FLyhioq2a7ZGwaj7ye9dlKRT5AePoyc/DP/qSnlLfDXCMf0o67vG6xQTu3dpaCjgPoe0TKeKPD/N1Lav1lMiQCReQag6yowHGLuOlslkjjNr2Llo98nmpJf1cKdZTVoBIelkxotsOC4PZXkYQk8B0GOhneA1bPuUP34JlFYO0silyWUNMiBwLObJOBFk8EjJ7rl1ufMSGlA9hjbOt/whfaaj01FkDdBvdUirtMQ75BxEeWZGen3c7PF5Sct5VVd3iIQ/ox59vOU74Es1g4qxXfBgHsyniWcLGl0yWffUa7cboNsceLhTXQIOvijlEip5cRlhQ18qO0nHbmdM30vsluyMQh29/JfJqthuOkvp7XiCFLQ8WiTCkpK8IsHF+u4vmMtucp6Hl+2Xps5NiPi9yR3oHhsnCZPdq+kgfhC3E8bf3vLMHJtYqy1X5RvlpSvymJZzD9ZvJDni8LBBlZF5DBF2NoP+g=
